# Generated by Django 4.1.4 on 2022-12-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_au', models.FloatField(default=0.0)),
                ('userAs', models.CharField(default='', max_length=50)),
                ('session_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_name', models.CharField(default='Неизвестная категория', max_length=255, unique=True)),
                ('subscribers', models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default=1, max_length=2)),
                ('datecr', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(default='', max_length=5000)),
                ('rating_post', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_to_many_postcatct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwsportal.category')),
                ('one_to_many_postcatpst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwsportal.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='nwsportal.PostCategory', to='nwsportal.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='one_to_many_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nwsportal.authoruser'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcomm', models.TextField(max_length=500)),
                ('datecomm', models.DateField(auto_now_add=True)),
                ('rating_comment', models.FloatField(default=0.0)),
                ('one_to_many_commau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nwsportal.authoruser')),
                ('one_to_many_commpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwsportal.post')),
            ],
        ),
    ]
