# Generated by Django 4.1.2 on 2022-10-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwsportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='userAs',
            field=models.CharField(default='', max_length=50),
        ),
    ]
